export const BOOKING_STATUS = {
  REQUESTED: 'REQUESTED',
  DRIVER_ASSIGNED: 'DRIVER_ASSIGNED',
  CONFIRMED: 'CONFIRMED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  NEEDS_REASSIGNMENT: 'NEEDS_REASSIGNMENT',
  CANCELLED: 'CANCELLED',
} as const;

// Allowed transitions — enforced server-side. No payment states: the
// customer pays the driver directly at trip completion (see PAYMENT_METHODS).
export const BOOKING_STATUS_TRANSITIONS: Record<string, string[]> = {
  REQUESTED: ['DRIVER_ASSIGNED', 'CANCELLED'],
  DRIVER_ASSIGNED: ['CONFIRMED', 'NEEDS_REASSIGNMENT', 'CANCELLED'],
  CONFIRMED: ['ONGOING', 'NEEDS_REASSIGNMENT', 'CANCELLED'],
  ONGOING: ['COMPLETED'],
  COMPLETED: ['CLOSED'],
  NEEDS_REASSIGNMENT: ['DRIVER_ASSIGNED', 'CANCELLED'],
  CANCELLED: [],
  CLOSED: [],
};
