export enum BookingStatus {
  REQUESTED = 'REQUESTED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  CONFIRMED = 'CONFIRMED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  NEEDS_REASSIGNMENT = 'NEEDS_REASSIGNMENT',
  CANCELLED = 'CANCELLED',
}
